name: rawae_gp24
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2 
  google_fonts: ^6.2.1
  delightful_toast: ^1.1.0
  get_it: ^8.0.0
  firebase_core: ^3.6.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
